### PR TITLE
failing test for #12

### PR DESCRIPTION
**Pull request by ags799**
Hey @kropp, here's a failing test to show we have still have some trouble with #12. I'm happy to develop the fix, but I may need a little help. How do I regenerate the generated code in `gen`?

### CODE REVIEW

**Comment by ags799** [comment]
I've made changes to `Makefile.BNF` but I'm not noticing any changes to the `gen` directory after running `./gradlew buildPlugin`.

**Comment by kropp** [comment]
Hi Andrew,
thanks for your contribution!
I've added a section to Readme file on how to regenerate parser and/or lexer.
You need to install plugin https://plugins.jetbrains.com/plugin/6606-grammar-kit
Then open parser or lexer definition and Ctrl+Shift+G will regenerate it.
I've also set up TeamCity integration, so all following pull requests will be built automatially.

**Comment by ags799** [comment]
Thanks for the help @kropp. I've installed the Grammar-Kit plugin.

I've tried to regenerate the parser definition, but nothing happens. I'm certain that I'm using the right hotkey.

I think there's that the `Makefile.bnf` isn't being parsed correctly. Should I expect to see this error in `Makefile.bnf` (on `master`)?

screen shot 2017-08-27 at 3 31 12 pm

This error persists after running `./gradlew clean buildPlugin`.

My Intellij version:
```
IntelliJ IDEA 2017.2.2
Build #IC-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

My Grammar-Kit version: `1.5.2`

**Comment by kropp** [comment]
@ags799 file icon gives a hint, that the file is mistakenly recognized as Makefile, while it should be BNF. You can check file associations in Settings → Editor → File Types

**Pull request closed without merging**
